apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vnplaterec-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yangchann/vnplaterec-frontend.git
    path: Kubernetes
    targetRevision: HEAD
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
