apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnplaterec-frontend
  labels:
    app: vnplaterec-frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnplaterec-frontend
  template:
    metadata:
      labels:
        app: vnplaterec-frontend
    spec:
      containers:
      - name: vnplaterec-frontend
        image: giangttc/vnplaterec-frontend:v20250601-b20421b
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"

        # Add resources limits and requests
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        # Add health checks
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
