apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnplaterec-frontend
  labels:
    app: vnplaterec-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnplaterec-frontend
  template:
    metadata:
      labels:
        app: vnplaterec-frontend
    spec:
      containers:
      - name: vnplaterec-frontend
        image: giangttc/vnplaterec_frontend:latest
        ports:
        - containerPort: 2106
          name: http
