apiVersion: v1
kind: Service
metadata:
  name: vnplaterec-frontend-service
  labels:
    app: vnplaterec-frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 2106
    nodePort: 30007
    protocol: TCP
  selector:
    app: vnplaterec-frontend
