apiVersion: v1
kind: Service
metadata:
  name: vnplaterec-frontend-service
  labels:
    app: vnplaterec-frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30007
    protocol: TCP
  selector:
    app: vnplaterec-frontend
