name:  Docker build, push and Trivy scan

on:
  workflow_call:
    inputs:
      TIMESTAMP:
        required: true
        type: string
        description: 'Timestamp for the Docker image tag'
    secrets:
      DOCKERHUB_TOKEN:
        required: true
        description: 'DockerHub token'
      DOCKERHUB_USERNAME:
        required: true
        description: 'DockerHub username'

jobs:
  dockertrivy:
    runs-on: ubuntu-latest
    name: Docker Build, Push and Trivy Scan
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ inputs.TIMESTAMP }}


        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        # build-args: |
        #   NODE_ENV=production
        #   NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL || 'https://localhost:8081' }}

    - name: Run Trivy vulnerability scanner in image mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ inputs.TIMESTAMP }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy report to Github Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif
